### ISSUE TITLE
Scroll bar is missing in 2.2.2

### ISSUE THREAD

**Issue by admurton** [kaaholst/android-squeezer#677]
In v2.2.2 the scroll bar is missing. You can still scroll the items but the scroll bar is needed for large collections

**Comment by kaaholst** [comment]
Unfortunately the fast scroller is missing in the latest version, this is not intended. We're working on a fix. It will be restored in the next version.

Thank you!

**Comment by admurton** [comment]
Thanks for the response. Do you know when the next version will be released?

I meant to mention that it is a great app!

**Comment by kaaholst** [comment]
I will make a new release just with the scroll bar. I hope to upload it to the beta channel this weekend. Then Google needs some days to approve it.

Opt in to receive beta versions of Squeezer by going to https://play.google.com/apps/testing/uk.org.ngo.squeezer and clicking the "Become a tester" button. You can opt out of the beta programme any time.

Otherwise please wait for the official release, which, provided there are no issues with the beta version, will be in a week or so.

**Comment by mobley-m** [comment]
Thanks for the fix - a big improvement over the old scroll bar too! Also wanted to record my appreciation for your efforts and those who have contributed in the past. Thanks!
Mike

**Comment by admurton** [comment]
I'd like to add my thanks as well

Ad

**Comment by kaaholst** [comment]
The scroll bar is back in 2.2.3, so closing this.

Thank you!
