### ISSUE TITLE
UI flapping (suspect WiFi roaming related)

### ISSUE THREAD

**Issue by climategadgets** [kaaholst/android-squeezer#691]
(Possible duplicate of #660, #680, but with more background information)

### Expected Behavior

Once connected, Squeezer stays connected as long as the device is on the same WiFi network.

### Actual Behavior

Squeezer starts, functions for a short period of time (10 seconds or so), then momentarily loses connection and shows as connected again, though the context is completely lost. This keeps repeating indefinitely.

### Suspected Root Cause

This behavior is observed when the device is located in a zone where the WiFi connection is likely to flap between two or more APs serving the same SSIDs. If Squeezer analyzes the WiFi connection status to control its behavior, it is quite possible that the callback sequence for switching from one AP to another is "Wifi Disconnect; WiFi Connected" which causes Squeezer to behave exactly as observed.

**Comment by kaaholst** [comment]
Version 2.2.4 which has just been released, contains a fix to circumvent the disconnection issue. Please report back here, if this is not the case.

Thanks for the feedback, it's appreciated.

I have two AP's with the same SSID, and don't experience this issue, so I don't think that's what's causing the issue, at least not on its own.

I have not found the root cause, instead version 2.2.4 reconnects (rehandshake) without loosing the context. I guess this would be the same solution, even if Wi-Fi-flapping is causing periodic disconnects. Squeezer does not monitor Wi-Fi connection, we just use whichever connection the device have.
