### ISSUE TITLE
Feature Request: lock screen widget

### ISSUE THREAD

**Issue by koendra** [kaaholst/android-squeezer#697]
Hi,

Would really appreciate a widget (not sure if this is the right word) on the lock screen: pause, forward and preferably also control volume through the built-in volume buttons. This all instead of unlocking the phone, opening the app (again) etc.

Or am I overseeing an already existing feature? (Googled but did not find anything)

Thanks a lot and keep up the good work!

**Comment by kaaholst** [comment]
The "Squeezer ongoing notification" channel should appear on the lock screen from Android version 5 and newer.
From Android 8.0 and newer you can disable or enable lock screen notifications for each notification channel.
On my phone on the lock screen I can: forward/backward and pause/play. Volume is currently not possible.

Here's a link on how to [Control notifications on Android](https://support.google.com/android/answer/9079661?hl=en)

Hope this helps, otherwise please report back.

**Comment by koendra** [comment]
Thanks, this really helped.

I rechecked the notifications, all possible permissions were given. So uninstalled and reinstalled Squeezer... that did the trick.

On my phone, there are only two options: forward and pause/play. Might have to do with screen size (small phone)? Nothing to really worry about btw, low low prio.

Volume would be much appreciated, my girlfriend is nagging me that "Spotify can change volume"... ;)

**Comment by kaaholst** [comment]
Not sure if you see this comment, however with the latest version of Squeezer, you can now control the volume via hardware volume keys, when the phone is locked.

**Comment by koendra** [comment]
Thanks kaaholst, have much appreciated your comment and are still appreciating the new feature!
