### ISSUE TITLE
edit home screen widget/ icons?

### ISSUE THREAD

**Issue by xpseudonym** [kaaholst/android-squeezer#704]
Hi, I feel sure I'm missing something - but, how do I edit the home screen widget/ icons?

If there's no way - then, a feature request?

I have both the BBC App and Deezer App on the home screen - but, also under My Apps.  I only need them in one place and they're taking up real estate on home screen - how can I remove them for the home screen.

Thanks.

**Comment by kaaholst** [comment]
Currently Squeezer does not support setup on the home menu on it's own, we rely on the menu we get from LMS.

For those Apps, at least the Deezer App, you can control whether it's displayed on the home screen via mysqueezebox.com. 

1. Go to mysqueezebox.com in a browser.
2. Log in with your credentials
3. Select the My Apps tab 
4. Select the Deezer or BBC App.
5. Select Player Settings

Here you can, for each player, select whether the to show the App on the screen.

Hope this helps, otherwise please report back.

**Comment by xpseudonym** [comment]
It looks like that worked for Deezer but there was nothing to do in BBC App.  Thanks
