### ISSUE TITLE
Play as next should be default when clicking track

### ISSUE THREAD

**Issue by pfavr** [kaaholst/android-squeezer#705]
While adding tracks to current playlist one can easily make the mistake of replacing the current playlist with just a single track or an album.

Please consider making default action when clicking a track or album "append to playlist" or "play as next". Maybe make this an option in settings?

**Comment by kaaholst** [comment]
The action which happens when an item is selected in Squeezer is controlled by LMS. This action can be configured via the players screen. Select the 3-dot menu in the top right, then select Players. In the players screen select the 3-dot menu to the right of the current player. The "Play Other Songs In Album" and "Defeat destructive Touch-To-Play" menu entries, controls this.

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still encounter this issue.

Thank you!
