### ISSUE TITLE
Feature request: Button for players screen in the top bar

### ISSUE THREAD

**Issue by billmax76** [kaaholst/android-squeezer#707]
After the latest update to 2.2.5 all volume controls are missing from their previous location in the players screen, which is now mostly empty.

**Comment by kaaholst** [comment]
You are right, that's a bug. I've just pushed a new version which has a fix for this. It should be available as soon as it's approved by Google.

Thanks for the feedback.

**Comment by eremem** [comment]
Would it be possible to put a button leading to this screen on the toolbar in the client's view, at least when in landscape mode? I mean the view with icons for search, playlist and view...
I recall seeing it a year or so ago but it's been removed afterwards. It was a lot more convenient and quick-to-reach on my tablet compared to the only option left now - selecting the command from the "context" menu.

**Comment by kaaholst** [comment]
The volume controls in the players screen has been fixed in version 2.2.6.
I've changed the headline for this issue to reflect the feature request for a shortcut to the players screen in the toolbar.

**Comment by kaaholst** [comment]
I've changed so it displays the buttons which fit on the top bar, otherwise they will go to the overflow menu (the 3-dot menu on the top right). 

See example screenshots below.

Pixel 3a:
![billede](https://user-images.githubusercontent.com/428304/120240375-ae309300-c260-11eb-89db-cf656284f8e4.png)
![billede](https://user-images.githubusercontent.com/428304/120240282-73c6f600-c260-11eb-95cb-61004232bd90.png)

7-inch tablet:
![billede](https://user-images.githubusercontent.com/428304/120239566-dc14d800-c25e-11eb-9710-0521a79633cd.png)
![billede](https://user-images.githubusercontent.com/428304/120239722-3150e980-c25f-11eb-9a28-90d292cd02d3.png)

**Comment by eremem** [comment]
Perfect! That looks really good. Thank you and I hope to see it soon on my display too:D.

**Comment by kaaholst** [comment]
This is fixed in 2.2.7 so closing this.

Thank you!
