### ISSUE TITLE
Material Icons for generic folders/categories

### ISSUE THREAD

**Issue by cucko** [kaaholst/android-squeezer#745]
Do you have in plan to change the current icons with material ones (to match the material skin for squeezeserver) ?
If you don't have time, i think i can help.

![image](https://user-images.githubusercontent.com/653097/150336907-3e454268-f9b7-4ce5-943e-dc6fc23e47c4.png)

**Comment by kaaholst** [comment]
Hi,

Any help is appreciated, thank you.

While there are no plans to match the material skin, there is a plan to adapt the LMS icons so they fit better for an app which uses material design.
Some icons are in place, they can be found [here](https://github.com/kaaholst/android-squeezer/tree/develop/Squeezer/src/main/res/drawable), e.g. [ml_new_music](https://github.com/kaaholst/android-squeezer/blob/develop/Squeezer/src/main/res/drawable/ml_new_music.xml).
The main issue is that some of these icons come from LMS (sent over the network run-time to Squeezer), and some are embedded in the Squeezer app. When they are sent over the network, LMS adds a background (with a different color and rounded corners) to the icon. To make it look consistent Squeezer currently also adds a background to the embedded icons.

Thus in order to use flat-icons we need to:

1. Create all icons embedded in Squeezer
2. Make Squeezer use the embedded icons instead of the one from LMS.

To see how this would look you can check the Spotty- or the DenonAVP-plugins. They send icons without this background.

I hope all this makes sense!

Regards 
Kurt

**Comment by kaaholst** [comment]
Flat icons are available from version 2.3.0, so closing this. Thank you!
