### ISSUE TITLE
Simple Volume Slider possible?

### ISSUE THREAD

**Issue by hurzl** [kaaholst/android-squeezer#766]
Why do I have to popup a window and then fiddle with a rotator-simulator to change volume, which mostly doesn't work? Can't it be more accessible?

**Comment by kaaholst** [comment]
You can use the device's volume up/down hardware buttons. They're always available.

**Comment by hurzl** [comment]
Yes I know

**Comment by kaaholst** [comment]
Currently there are volume sliders on the players page (select three dot menu on the top right, then Players).
Are you requesting a slider like that to be always visible, e.g. on the now playing screen, if you are on a device where there is room for it?

**Comment by hurzl** [comment]
There is lots of room on the phone display, but still you have to first popup the volume control, then pop it up again after 5 seconds, because then it also disappears (why?). It could be much easier and less complicated to just have a slider on the screen.

**Comment by hurzl** [comment]
If you pack the bottom area a little bit more, there is enough room for another line.
Or you could replace the "Change Volume" text by a slider and make "Playlist" icon-only (and even move that 1 or 2 lines up).
And make the speaker icon toggle mute.

**Comment by kaaholst** [comment]
Those are good suggestions thank you.

Packing it more I think will be complicated because we have to support all sort of different shapes and sizes.

Replacing Change volume by a slider would be consistent with how the players screen volume sliders look and works, including mute via the speaker icon. Where/how to put playlist and volume settings may need some experiments.

I will explore this later.

Thanks for the suggestions!

**Comment by hurzl** [comment]
Ok thank you, but while it's open I can't do anything else. So it doesn't help. I don't understand why you need this big circular control which is more difficult to use anyway.

**Comment by kaaholst** [comment]
This is fixed in version 2.3.5, so closing this
