### ISSUE TITLE
Option to switch back from 'Flat Icons'

### ISSUE THREAD

**Issue by MicPra** [kaaholst/android-squeezer#773]
I just got the 2.3.0 beta-1.  So far everything looks good.  However, I don't like the new 'flat icons' that much.  Unfortunately, this also results in an icon mix with sub menus.  In the final release, may you please add the possibility to alternatively switch to the old icons as they are passed to Squeezeplay/jive from the LMS including the background.  That would be great and would restore the consistent look.

Thanks for your continues great work on Squeezer!

**Comment by cathcam** [comment]
Are the new flat icons sent from the server, are they user replaceable on the server or the client side?

The "my music" flat icon doesn't even make sense in our home. We have three people with phone apps and the music comes from NAS via a small server in a basement and never plays on a laptop.

The new function to bypass a VPN works great though, so thanks for that.

**Comment by kaaholst** [comment]
Thanks for constructive feedback!

Unfortunately, it's not as simple as just using the icons as passed from LMS. The reason is that sometimes we receive an icon-ID or icon-URL which we are supposed to fetch from LMS. Sometimes we just get an ID for the menu-item, and the icon is expected to be embedded in the client (Squeezer).

I'm sure we will find a solution, though. Basically what I did for this release, is removing the background (and gradients) from the embedded icons. I can add an option to use flat icons or not. If not, then re-add the background to the embedded icons?

@cathcam If I understand the comment correct, you are referring to the icon for My Music looks like a laptop?
If so, I agree. I will see if what I can find. Note that the laptop is not new, it is, like all (most) other flat icons, the standard LMS icon without the background.

**Comment by cathcam** [comment]
Yes, I get that it's not a simple change, this has been an issue for a while and possibly needs a better structure/design on the server side rather than continual hacking on the client side to find a way around.

Mine is really an NFR. The musical note inside a laptop screen makes no sense for us and I suspect any one who doesn't use a laptop to run or access LMS. A simple solution would be just a large musical note in the center with the word "My" in the top left as big as would make sense.

I'm not a graphic/UI designer but would happily hack around trying to create one if you would like to give me the specs. pixel height, width; DPI, format(JPG, ICO, PNG).

Thanks for taking time to respond.

++Mark. 
https://ctproduced.com

**Comment by MicPra** [comment]
@kaaholst , thanks for the detailed explanation. An option to use flat icons or not and re-add the background in the not-option sounds perfect.

Just for your information...the beta-1 seems to be really stable on my system. Great work!

**Comment by kaaholst** [comment]
I have uploaded a new beta version, which I just got informed is now online. I added an option in the view menu to choose whether to use flat icons or add the background to the icons. Furthermore, I made a new icon for my music.

This option applies to icons embedded in the app, so for example for Spotty it will always be flat icons regardless of this new selection, but for internet radio icons will always have background. I agree, a server side solution would be preferable to avoid this confusion.

Thanks for the feedback, it's appreciated. Also, thanks for the info, the beta version is stable.

**Comment by MicPra** [comment]
Hey @kaaholst , wow... nice work! Your icons look great... but I also agree that a server side solution would be preferable to avoid different looking icons.

Maybe this could be a request for mherger and the upcoming lms 8.4. You could try to align with him :-D

For stability issues - I do not see any misbehaving up to now

**Comment by cathcam** [comment]
Thank you. The options to view the icons flat on/off is perfect as is 
the new icon for my music. I'll report back if I have any problems.

++Mark.
______________________
https://ctproduced.com
https://markcathcart.com/about/

**Comment by cucko** [comment]
suggestion about removing the gray border on the icons provided by server, check android.graphics.blendMode
https://developer.android.com/reference/android/graphics/BlendMode
i think you can use one blank bitmap (only the border without the icon, maybe it will need transparency or some small modification) and compose it over the icon provided by server, that will remove the border and light gray background. i'm not sure which blend mode will do that, but you can play with the modes on the link above and see which one will do the job.

**Comment by kaaholst** [comment]
@cucko I will look into handling the icons from the server for a later Squeezer release. I will check out your suggestion. Even if it probably qualifies as a client side hack. :-)
Thanks for the input!

**Comment by MicPra** [comment]
I like the icons as they are... incl. the gray border. For me it is important that as much as possible looks identical on different displays, so I prefer things are deployed from the server. 

By the way great work so far. The beta seems to be really stable! Thanks a lot!

**Comment by kaaholst** [comment]
This is available from version 2.3.0, so closing this. Thanks for the feedback!
