### ISSUE TITLE
"Home list" popup menu misbehaving after server upgrade? database rebuild?

### ISSUE THREAD

**Issue by climategadgets** [kaaholst/android-squeezer#783]
Oh boy, is this a weird one :)

### Expected Behavior

A song on a "home list" displays a popup menu when the three dot menu is short pressed

### Actual Behavior

The action results in an endlessly spinning circle

### Contributing Factors

This has been observed for *only old entries* after the server upgrade from 7.9 to 8.3 (which, in turn, requested a full database rebuild because the schema changed). Entries added to the home list after the upgrade behave normally. It is as if the menu is built using transient identifiers that are wiped out either by a server upgrade, or a database rebuild.

**Comment by kaaholst** [comment]
Hi,

Sorry for the late answer. If you still experience this, I suggest trying the [forum](https://forums.slimdevices.com/). I think it's a server (LMS) issue.

Here's how Squeezer works. There are more details, but in principle it's like this. When we display a page, we display the items we receive from LMS. For each item, we may receive a “go” action and a “more” action. When an item is selected, we send the go action to LMS, and display the items we receive on a new page. When the three dot menu is selected, we send the more action to LMS and display the items we receive in a popup. While waiting for the items, we display a spinning circle. If the spinning circle pertains, it is because we don't receive a response from LMS.

**Comment by climategadgets** [comment]
No worries, life is life.

Yep, you're describing exactly what I thought is going on behind the scenes. It may have been that the server was doing shadow rebuilds on old entries, and that was causing a delay.

The issue is no longer observed; I'll keep an eye on it during next server upgrade.

**Comment by climategadgets** [comment]
An update: it looks like it's the complete library rescan causes this.

### To Reproduce
1. Add an item to the home screen by long pressing on a track in a list;
1. Confirm that it is working correctly by pressing the triple dot menu;
1. Perform a full library rescan.

### Expected Behavior
Pressing the triple dot menu opens the floating action menu.

### Actual Behavior
The action results in an endlessly spinning circle, as originally reported.

### Additional Context
* Is it possible that Squeezer retains a reference to a track the Squeezebox server no longer has after a full rescan?
* If that's the case, since Squeezer still has the correct metadata on the track, is it possible to recover the lost track reference by, say, initiating two requests in parallel (one as it did before that results in success unless there was a rescan, and the other as "search" that might return the same track possibly slower but still with a valid hit) and then choosing the first answer that came back (since it looks like the Squeezebox Server just doesn't send anything back if it gets a wrong reference)?

**Comment by kaaholst** [comment]
Thanks for the detailed information, well spotted!
I think you're right, the references changes after a server rescan, which causes the configured shortcuts to fail.
Squeezer keeps track of the time for last rescan, so we do know when there has been a rescan. We'll think about what we can do, it seems that attempting to use the meta-data is the best option.

**Comment by kaaholst** [comment]
This is available from version 2.3.7, closing this. Thank you!
If you still experience the issue, feel free to reopen.

**Comment by climategadgets** [comment]
A twist: different backend over the same collection. I moved from a server running on a general purpose Pi box to https://www.picoreplayer.org/, and this issue resurfaced. Sure thing, it's a different server now and different internal data, but the tracks are the same :)

Side note, how will this list behave if connected to a different server? Is the list Squeezer wide, or connection specific? Either way, it would be nice to identify the track regardless of which server Squeezer is connected to; here's a use case: more than one person in the household listening to different subsets of the same big collection. There will definitely be overlaps between those subsets, so making this list Squeezer wide makes sense - and so does identifying whether a particular list entry doesn't exist on a particular connection.

**Comment by kaaholst** [comment]
The shortcuts are stored on the Android device running Squeezer. We don't put any information on server (or player) in the storage. So this means that different servers aren't really supported.

The stored shortcuts are simply the item we receive from LMS. As these can contain internal LMS references, this mechanism isn't really supported by LMS either.

To work around this, we have implemented the following workaround.

When Squeezer connects to a server, we subscribe to server status messages, which contains the time the library is last scanned. When we receive a server status message, we compare the last scan time reported by the server, with the scan time from a previous server status message. If these times are different we attempt to update the shortcuts by searching for the item name in the relevant section of LMS, i.e. artists, albums, genres, and folders respectively. For folders and tracks this can be recursive (tracks, because for each album we can get a track list).

In theory, this could work if you switch to a new server with the same tracks. Because the item names are the same, but the server scan times are unlikely to match.

Unfortunately, it turns out that, the server scan time changes every time a folder is opened, So the update of shortcuts occurs too often and causes performance issues. So I had to disable the recursive part of it.
