### ISSUE TITLE
A52 can manage squeezebox touch but impossible to manage the phone

### ISSUE THREAD

**Issue by Tchantches65** [kaaholst/android-squeezer#805]
Hello,
Sorry, i'm a newbee. I have 2 squeezebox's and LMS on a Synology. I install Squeezer on my Samsung A52. I see the 2 squeezebox's but not my phone on my phone. I see it on musqueezebox.com.

What can I do ?

**Comment by kaaholst** [comment]
Squeezer is a remote control for LMS players only, it does not stream music on its own. It connects to your LMS and controls the players which are connected to the LMS. To use your phone as a player, you need to install a player app. The reason you see your phone on mysqueezebox.com, I think, is because you have connected to it from Squeezer. (it does not distinguish between players and controllers).

**Comment by Tchantches65** [comment]
Tanks for your answer.

Le lun. 11 déc. 2023, 22:08, Kurt Aaholst ***@***.***> a
écrit :
