### ISSUE TITLE
Disable/Enable all Alarm Clocks

### ISSUE THREAD

**Issue by Foksadure** [kaaholst/android-squeezer#811]
Hello,

The radio buttons popup to Disable/Enable all alarm clocks is not working properly on my Android devices (mostly Android 14).

I think an "All Alarm clocks enabled" line with a checkbox on the menu would do just fine instead, and be more convenient on touchscreens. Visual feedback for the all alarm clocks status would be immediate as well.

Thanks for Android Squeezer!

👍

**Comment by kaaholst** [comment]
I have found an unfortunate behavior in Squeezer, which may be what you experience. When you select disable/enable all alarms from the popup buttons, the command to disable/enable alarms is sent to the server, so the setting is changed. But the state is not updated in Squeezer, so when you open the popup again, it still shows the old setting. To verify this, and as a workaround, you can press the back button to close the alarm settings page. Then open it again, and open the popup for to enable/disable all alarms, which should then show the correct value.

This will be fixed in the next version. Visual feedback will also be immediate in the next version. 

What we show in these pages is controlled by the server, so we can't change that (we can change how we show it, though). An alternative is to use the local implementation of alarm settings, available via the 3 dot button on the top right. This does not suffer from the above, and has the switch toggle that you request. 

Thanks for the feedback!

**Comment by Foksadure** [comment]
Thanks for the detailed explanation and the workaround.
I'm usually managing those settings in LMS WebGUI anyway.
Looking forward the next update.

**Comment by kaaholst** [comment]
This is fixed in version 2.3.6, so closing this. Thank you!

**Comment by Foksadure** [comment]
Thanks!
