### ISSUE TITLE
Search function does not work

### ISSUE THREAD

**Issue by EF1973** [kaaholst/android-squeezer#813]
Since the last update of squeezer the search function does not work anymore as it did. It does not make a difference what I fill in it gives as result 1 for each option (number/album etc.) and that is .. I hope there is a solution because it is a very easy function.

**Comment by kaaholst** [comment]
We are not aware of any issues of the search function, so this may be an issue with your local server.

We did make a change a couple of versions back, that the number of search result is not shown until the list is expanded. This change was made because it turned out that merely executing the nested searches in some cases actually performed a change.

Or did you mean something else?

**Comment by EF1973** [comment]
Hi Kurt,

Thanks for your reply. I will make a new scan of my music collection and
try again.

Op wo 6 mrt 2024 om 08:29 schreef Kurt Aaholst ***@***.***>:

**Comment by EF1973** [comment]
The problem was solved by removing all music and scan again. It probably was something like and index issue.
